In [1]:
import numpy as np 
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [6]:
df=pd.read_csv('../dataset/covid_toy.csv')

In [7]:
df.sample()

    age  gender  fever   cough   city has_covid
17   40  Female   98.0  Strong  Delhi        No

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),
#                                                df['has_covid'],
#                                                test_size=0.2)
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2)

In [15]:
X_train

    age  gender  fever   cough       city
49   44    Male  104.0    Mild     Mumbai
80   14  Female   99.0    Mild     Mumbai
57   49  Female   99.0  Strong  Bangalore
55   81  Female  101.0    Mild     Mumbai
37   55    Male  100.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
76   80    Male  100.0    Mild  Bangalore
31   83    Male  103.0    Mild    Kolkata
62   56  Female  104.0  Strong  Bangalore
0    60    Male  103.0    Mild    Kolkata
39   50  Female  103.0    Mild    Kolkata

[80 rows x 5 columns]

## without using column transformer

In [16]:
si =SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])

X_test_fever=si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [20]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])

In [18]:
X_train_cough.shape

(80, 2)

In [23]:
ohe=OneHotEncoder(drop='first')
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])
X_train_gender_city.shape

(80, 4)

In [27]:
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values

In [30]:
# X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)
# X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis=1)

## by using the column transformer

In [32]:

from sklearn.compose import ColumnTransformer

In [34]:
ttransformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

In [35]:

transformer.fit_transform(X_train).shape

NameError: name 'transformer' is not defined